# docker-compose.yml for the mpop_service
# See also the Dockerfile

version: '3'

services:

  cron:
    build: ./mysqldump
    # image: schnitzler/mysqldump
    restart: always
    volumes:
      - ./mysqldump/crontab:/var/spool/cron/crontabs/root
      - ./mysqldump/backup.sh:/usr/local/bin/backup.sh
      - ./backups:/backups
    command: ["-l", "8", "-d", "8"]
    environment:
      MYSQL_HOST: 'db'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'secret'
      MYSQL_DATABASE: 'mpop_database'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_USER: 'admin'
      PMA_PASSWORD: 'secret'
    depends_on:
      - db
    ports:
      - "8088:80"

  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'mpop_database'
      MYSQL_ROOT_PASSWORD: 'secret'
      MYSQL_USER: 'admin'
      MYSQL_PASSWORD: 'secret'
      TZ: 'America/Toronto'
    ports:
      # Exporse port 13306 - In case we need it. Just for debugging purposes:
      - "13306:3306"
    
  flyway:
    image: flyway/flyway
    command: -url=jdbc:mysql://db:3306/mpop_database?verifyServerCertificate=false&useSSL=false -user=root -password=secret -connectRetries=60 migrate
    volumes:
      - ./flyway/sql:/flyway/sql
    depends_on:
      - db

