-- Create tables for the MPOP database

CREATE TABLE IF NOT EXISTS tag
(
  id BIGINT UNSIGNED NOT NULL PRIMARY KEY,
  rfid VARCHAR(256) NOT NULL UNIQUE,
  visitor_id BIGINT UNSIGNED NULL UNIQUE,
  last_used_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS visitor
(
  id BIGINT UNSIGNED NOT NULL PRIMARY KEY,
  gender VARCHAR(6) DEFAULT 'other',
  language VARCHAR(2) DEFAULT 'fr',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS answer
(
  id BIGINT UNSIGNED NOT NULL PRIMARY KEY,
  question_identifier VARCHAR(100),
  value TINYINT UNSIGNED,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

